# log level can be (debug, info, warn, error, panic, fatal)
log_level: "debug"

# certificates and keys
private_key: "configs/controller/client.key"
public_key: "configs/controller/client.crt"
cac: "configs/ca.crt"

# iptable maps all clients and nodes to their ip and metadata
iptable:
  nodes:
  - key: "S1"
    value: "127.0.0.1:5001"
    metadata: 0
  clients:
  - key: "A"
    value: "127.0.0.1:6001"
    metadata: 10

# controller app configs
controller:
  csv: "tests/sample.csv"
