# log level can be (debug, info, warn, error, panic, fatal)
log_level: "debug"

# certificates and keys
tls:
  private_key: "configs/nodes/S3/server.key"
  public_key: "configs/nodes/S3/server.crt"
  ca_key: "configs/ca.crt"

# iptable maps all clients and nodes to their ip and metadata
iptable:
  - key: "S1"
    value: "127.0.0.1:5001"
    metadata: 0
  - key: "S2"
    value: "127.0.0.1:5002"
    metadata: 1
  - key: "S3"
    value: "127.0.0.1:5003"
    metadata: 2
  - key: "S4"
    value: "127.0.0.1:5004"
    metadata: 3
  - key: "S5"
    value: "127.0.0.1:5005"
    metadata: 4
  - key: "S6"
    value: "127.0.0.1:5006"
    metadata: 5
  - key: "S7"
    value: "127.0.0.1:5007"
    metadata: 6
  - key: "client"
    value: "127.0.0.1:6001"
    metadata: -1

# list of clients
clients:
  - key: "A"
    metadata: 10
  - key: "B"
    metadata: 10
  - key: "C"
    metadata: 10
  - key: "D"
    metadata: 10
  - key: "E"
    metadata: 10
  - key: "F"
    metadata: 10
  - key: "G"
    metadata: 10
  - key: "H"
    metadata: 10
  - key: "I"
    metadata: 10
  - key: "J"
    metadata: 10

# node app configs
node:
  port: 5003
  node_id: S3
  bft: # pbft configs
    total: 7
    majority: 5
    responses: 3
    majority_timeout: 100 # in milliseconds
    view_timeout: 1 # in seconds
    viewchange_timeout: 100 # in milliseconds
    newview_timeout: 100 # in milliseconds
