# log level can be (debug, info, warn, error, panic, fatal)
log_level: "debug"

# certificates and keys
tls:
  private_key: "configs/nodes/S1/server.key"
  public_key: "configs/nodes/S1/server.crt"
  ca_key: "configs/ca.crt"

# iptable maps all clients and nodes to their ip and metadata
iptable:
  - key: "S1"
    value: "127.0.0.1:5001"
    metadata: 0
  - key: "S2"
    value: "127.0.0.1:5002"
    metadata: 1
  - key: "S3"
    value: "127.0.0.1:5003"
    metadata: 2
  - key: "S4"
    value: "127.0.0.1:5004"
    metadata: 3
  - key: "client"
    value: "127.0.0.1:6001"
    metadata: -1

# list of clients
clients:
  - key: "A"
    metadata: 10
  - key: "B"
    metadata: 10

# node app configs
node:
  port: 5003
  node_id: S3
  core_node: true # core nodes
  bft: # pbft configs
    total: 4
    majority: 3
    responses: 2
    majority_timeout: 100 # in milliseconds
    view_timeout: 100 # in milliseconds
